import Head from "next/head";
import axios from "axios";
import { useEffect, useState } from "react";
import { Container, Row, Col } from "react-bootstrap";
import Gallery from "../components/home/Gallery";
import HomeTable from "../components/home/HomeTable";

export default function Home(props) {
  const menu = [
    { title: "구인", props: props.jobs },
    { title: "사고&팔고", props: props.jobs },
    { title: "비지니스", props: props.jobs },
    { title: "사고&팔고", props: props.jobs },
    { title: "비지니스", props: props.jobs },
  ];

  const [data, setData] = useState([]);
  useEffect(() => {
    setData(props.data);
  }, []);

  if (data) return <div>Loading...</div>;
  return (
    <Container id="home">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Row>
        <Col className="py-3">
          <Gallery />
        </Col>
      </Row>

      <Row className="py-4">
        {menu.map((item) => (
          <Col className="d-flex justify-content-center py-2">
            <div style={{ width: "250px" }}>
              <HomeTable title={item.title} jobs={props.jobs} />
            </div>
          </Col>
        ))}
      </Row>
    </Container>
  );
}
//fetch before rednering
export async function getServerSideProps(context) {
  const jobs = await axios
    .get("https://korean-community.herokuapp.com/find-jobs/1")
    .then((res) => res.data);
  return { props: { jobs } };
}
